name: Clear Trakt Playback Status

on:
  schedule:
    - cron: '*/30 * * * *'  # Esegue lo script ogni 10 minuti
  workflow_dispatch:  # Permette di eseguire manualmente il workflow se necessario

jobs:
  clear_playback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run clear playback script
        env:
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
          TRAKT_ACCESS_TOKEN: ${{ secrets.TRAKT_ACCESS_TOKEN }}
        run: python clear_playback.py
